### ISSUE TITLE
Minor credential / session fixes

### ISSUE THREAD

**Issue by AverageOrangeCat** [AverageOrangeCat/spring-boot-angular-concepts#1]
## must haves 🚩

- [ ] Add get and update function to session
- [ ] Add reduced credential option + authentication
- [ ] Add controller data mapper
- [ ] Enforce session expiration via background worker
- [ ] Add testing
- [ ] ...

## nice to have 🎉

- [ ] ...

## linked issues

- [ ] ...
